//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMaster
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Skills { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public string CandidatePhoto { get; set; }
        public string ResumeFile { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string Status { get; set; }
    }
}
