//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string ProjectDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
