//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeMaster
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
        public string Category { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
