//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicationMaster
    {
        public int Id { get; set; }
        public string CandidateName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string PositionAppliedFor { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string ResumePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
