//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioMaster
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
        public string Category { get; set; }
        public string Technologies { get; set; }
        public string ProjectUrl { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
