//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationList.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esankal1_esankalpEntities : DbContext
    {
        public esankal1_esankalpEntities()
            : base("name=esankal1_esankalpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<ApplicationMaster> ApplicationMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<JobApplicationMaster> JobApplicationMasters { get; set; }
        public virtual DbSet<IncomeMaster> IncomeMasters { get; set; }
        public virtual DbSet<PortfolioMaster> PortfolioMasters { get; set; }
    }
}
